import = ["/home/sttavos/.config/alacritty/gruvbox.toml"]

[window]
decorations = "full"
dynamic_title = true
opacity = 0.9
padding = { x = 5, y = 0 }

[shell]
program = "/bin/zsh"

# Font config:
[font]
size = 11.0

[font.bold]
family = "JetbrainsMonoNL Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetbrainsMonoNL Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "JetbrainsMonoNL Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetbrainsMonoNL Nerd Font Mono"
style = "Regular"
