# TODO: migrar para .lua no dia em que for possível

$color = rgba(29, 32, 33, 1.0)          # bg0_hard  #1d2021
$inner_color = rgba(60, 56, 54, 0.8)    # bg1       #3c3836
$outer_color = rgba(250, 189, 47, 1.0)  # yellow    #fabd2f
$font_color = rgba(235, 219, 178, 1.0)  # fg        #ebdbb2
$check_color = rgba(184, 187, 38, 1.0)  # green     #b8bb26

general {
    ignore_empty_input = true
}

background {
    monitor =
    color = $color
    # TODO: apontar para um wallpaper (mesmo do hyprpaper.conf)
    # path = ~/Pictures/wallpapers/gruvbox.png
    blur_passes = 3
}

animations {
    enabled = false
}

input-field {
    monitor =
    size = 650, 100
    position = 0, 0
    halign = center
    valign = center

    inner_color = $inner_color
    outer_color = $outer_color
    outline_thickness = 4

    font_family = JetBrainsMono Nerd Font
    font_color = $font_color

    placeholder_text = Enter Password
    check_color = $check_color
    fail_text = <i>$FAIL ($ATTEMPTS)</i>

    rounding = 0
    shadow_passes = 0
    fade_on_empty = false
}

auth {
    fingerprint:enabled = false
}
