# App-specific tweaks
source = ~/.config/hypr/omarchy/apps/1password.conf
source = ~/.config/hypr/omarchy/apps/bitwarden.conf
source = ~/.config/hypr/omarchy/apps/browser.conf
source = ~/.config/hypr/omarchy/apps/hyprshot.conf
source = ~/.config/hypr/omarchy/apps/jetbrains.conf
source = ~/.config/hypr/omarchy/apps/localsend.conf
source = ~/.config/hypr/omarchy/apps/pip.conf
source = ~/.config/hypr/omarchy/apps/qemu.conf
source = ~/.config/hypr/omarchy/apps/retroarch.conf
source = ~/.config/hypr/omarchy/apps/steam.conf
source = ~/.config/hypr/omarchy/apps/geforce.conf
source = ~/.config/hypr/omarchy/apps/moonlight.conf
source = ~/.config/hypr/omarchy/apps/system.conf
source = ~/.config/hypr/omarchy/apps/telegram.conf
source = ~/.config/hypr/omarchy/apps/typora.conf
source = ~/.config/hypr/omarchy/apps/terminals.conf
source = ~/.config/hypr/omarchy/apps/walker.conf
source = ~/.config/hypr/omarchy/apps/webcam-overlay.conf
